_BASE_: "Base-RetinaNet.yaml"

MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_50_FPN_3x/190397829/model_final_5bd44e.pkl"
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 1
  BACKBONE:
    FREEZE_AT: 2

SOLVER:
  STEPS: (30000,)
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.001

DATALOADER:
  NUM_WORKERS: 0

DATASETS:
  TRAIN: ('train_CLEAR_9-15',)
  TEST: ('val_CLEAR_9-15',)

INPUT:
  MIN_SIZE_TRAIN: (0,)
  MIN_SIZE_TEST: 0

OUTPUT_DIR: work_dir/DeepGTAV/CLEAR_9-15

